apiVersion: v1
kind: Service
metadata:
  name: friendsdrinks-api-service
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: friendsdrinks-api-service
