apiVersion: v1
kind: Service
metadata:
  name: frontendapi-cs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32751
      name: client
  selector:
    app: friendsdrinks-api-service
