apiVersion: apps/v1
kind: Deployment
metadata:
  name: avro-schemas
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: cp
        image: confluentinc/cp-schema-registry:7.7.1
        env:
        - name: SCHEMA_REGISTRY_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/schema-registry/log4j.properties
        - name: SCHEMA_REGISTRY_MASTER_ELIGIBILITY
          value: "true"
        - name: SCHEMA_REGISTRY_MASTER_ELIGIBILITY
          value: "true"
        - name: SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID
          value: "1"
        - name: SCHEMA_REGISTRY_HEAP_OPTS
          value: "-Xms512M -Xmx512M"
        command:
        - schema-registry-start
        - /etc/schema-registry-config/schema-registry.properties
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config
          mountPath: /etc/schema-registry-config
      securityContext:
        runAsUser: 0
      volumes:
      - name: config
        configMap:
          name: avro-tools-config
