apiVersion: v1beta
kind: Secret
metadata:
  name: docker-hub-secret
data:
  env_vars:
    - name: DOCKER_USERNAME
      value: $DOCKER_USERNAME
    - name: DOCKER_PASSWORD
      value: $DOCKER_PASSWORD
