apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topics-job
spec:
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      containers:
        - name: kafka-create-topics-job
          image: confluentinc/cp-kafka:6.2.0
          command:
            - sh
            - -c
            - "echo About to create topics... && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic frontend-responses && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-meetup-event && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-meetup-state && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-event && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-state && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-keyed-by-admin-user-id-state && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-membership-event && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-membership-state && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-membership-keyed-by-friendsdrinks-id-state && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-membership-keyed-by-user-id-state && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-api && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-invitation-event && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic friendsdrinks-invitation-state && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic user-event && \
               kafka-topics --create --if-not-exists --bootstrap-server bootstrap.kafka.svc.cluster.local:9092 --partitions 2 --replication-factor 1 --topic user-state && \
               echo Done creating topics...  \
                       "
      restartPolicy: Never
  backoffLimit: 2
