apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-service
spec:
  replicas: 1
  serviceName: "user-service"
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: $img
          env:
            - name: STREAMS_GROUP_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 2
            periodSeconds: 30
          ports:
            - containerPort: 8080
          args: ["andrewgrant.friendsdrinks.user.Service", "/app/config/dev-kubernetes.properties"]
      volumes:
        - name: config
          configMap:
            name: streams-config
